# Style/Documentation:
#   Enabled: false
# Style/BlockComments:
#   Enabled: false
# Metrics/LineLength:
#   Enabled: false
# Metrics/MethodLength:
#   Enabled: false
# Style/ClassAndModuleChildren:
#   Enabled: false 
Style/RaiseArgs:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - db/**/*
    - bin/rails
    - bin/rake
    - bin/rspec
