---
default: &default
  adapter: postgresql
  encoding: unicode
  host: "<%= ENV['DATABASE_HOST'] || 'localhost' %>"
  port: 5432
  username: postgres
  password: 24373514
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: 
  <<: *default
  database: allergen_manager_development

test:
  <<: *default
  database: allergen_manager_test

preparing:
  <<: *default
  database: allergen_manager_preparing
  host: "<%= ENV['DATABASE_HOST'] || 'localhost' %>"
  username: postgres
  password: root
  
production:
  <<: *default
  database: allergen_manager_production
  host: "<%= ENV['DATABASE_HOST'] || 'localhost' %>"
  username: postgres
  password: root
 