---
default: &default
  adapter: postgresql
  encoding: unicode
  host: "<%= ENV['DATABASE_HOST'] || 'localhost' %>"
  port: 5432
  username: postgres
  password: 24373514
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: 
  <<: *default
  database: allergen_manager_development

test:
  <<: *default
  database: allergen_manager_test

preparing:
  <<: *default
  database: "<%= ENV['DATABASE_DBNAME'] %>"
  host: "<%= ENV['DATABASE_HOST'] %>"
  username: "<%= ENV['DATABASE_USERNAME'] %>"
  password: "<%= ENV['DATABASE_PASSWORD'] %>"
  
production:
  <<: *default
  database: "<%= ENV['DATABASE_DBNAME'] %>"
  host: "<%= ENV['DATABASE_HOST'] %>"
  username: "<%= ENV['DATABASE_USERNAME'] %>"
  password: "<%= ENV['DATABASE_PASSWORD'] %>"
  pool: 50
 